language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
script:
  - bin/test
after_success:
  - bin/coverage run bin/test --test=\!"robot"
  - pip install coverage==4.5.4
  - python -m coverage.pickle2json
  - pip install coveralls
  - coveralls

notifications:
  email:
    - travis-reports@ecreall.com
